name: Pull requests

on: [pull_request]

jobs:

  staticAnalysis:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Static Analysis
        run: ./gradlew ktlintCheck detekt app:lintDebug custom:lintCustomexampleDebug

      - name: Upload Static Analysis Report
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Static Analysis Report
          path: |
            **/reports/


  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build all configurations
        run: ./gradlew assemble

      - name: Upload APK as Artifacts
        uses: actions/upload-artifact@v2.2.0
        with:
          name: kiwix-android
          path: |
            **/*.apk
